//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.27 at 09:54:00 PM BRT 
//


package net.baquara.dbservices.dbschema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.baquara.dbservices.dbschema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DbSchema_QNAME = new QName("", "db-schema");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.baquara.dbservices.dbschema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link TableData }
     * 
     */
    public TableData createTableData() {
        return new TableData();
    }

    /**
     * Create an instance of {@link TableSchema }
     * 
     */
    public TableSchema createTableSchema() {
        return new TableSchema();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link SuperUser }
     * 
     */
    public SuperUser createSuperUser() {
        return new SuperUser();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link DBSchema }
     * 
     */
    public DBSchema createDBSchema() {
        return new DBSchema();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DBSchema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "db-schema")
    public JAXBElement<DBSchema> createDbSchema(DBSchema value) {
        return new JAXBElement<DBSchema>(_DbSchema_QNAME, DBSchema.class, null, value);
    }

}
